import { copyFileSync, cpSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const source = join(root, 'src', 'host', 'index.js');
const pureSource = join(root, 'src', 'host', 'pure.js');
const contextSource = join(root, 'src', 'host', 'context-provider.js');
const promptSource = join(root, 'src', 'host', 'prompt');
const output = join(root, 'plugin-host.js');
const lib = join(root, 'lib', 'index.cjs');
const pureOutput = join(root, 'lib', 'pure.js');
const contextOutput = join(root, 'lib', 'context-provider.js');
const promptOutput = join(root, 'lib', 'prompt');

mkdirSync(dirname(lib), { recursive: true });
copyFileSync(source, lib);
copyFileSync(pureSource, pureOutput);
copyFileSync(contextSource, contextOutput);
cpSync(promptSource, promptOutput, { recursive: true });
writeFileSync(output, "// GENERATED by scripts/build-host.mjs - do not edit by hand.\nmodule.exports = require('./lib/index.cjs');\n", 'utf8');
console.log('Host bundle written.');
