import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const sourcePath = join(root, 'src', 'client', 'app.js');
const source = readFileSync(sourcePath, 'utf8');
const outputPath = join(root, 'lib', 'client.cjs');
const pluginPath = join(root, 'plugin-client.js');
const bundled = `// GENERATED by scripts/build-client.mjs - do not edit by hand.\nwindow.__ModuleLoader__.load({\n  id: 'zzy-dsh-prompt-optimizer',\n  factory: (require) => {\n    var module = { exports: {} };\n    var exports = module.exports;\n    const React = require('react');\n${source}\n    return module.exports;\n  },\n});\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(pluginPath, source, 'utf8');
writeFileSync(outputPath, bundled, 'utf8');
console.log('Client bundle written.');
